// Builds src/data/tracks.ts: one SVG outline per circuit the site shows, keyed by the
// circuit name Jolpica uses. Source: bacinger/f1-circuits (MIT, (c) Tomislav Bacinger),
// https://github.com/bacinger/f1-circuits. Run by hand when the calendar changes:
//   node scripts/build-tracks.mjs [path/to/f1-circuits.geojson]
// Without a path it downloads the file. The output is committed; the build never fetches.
import { readFileSync, writeFileSync } from 'node:fs'

const SOURCE = 'https://raw.githubusercontent.com/bacinger/f1-circuits/master/f1-circuits.geojson'

// Jolpica circuit name to the dataset's id.
const CIRCUITS = {
  'Albert Park Grand Prix Circuit': 'au-1953',
  'Shanghai International Circuit': 'cn-2004',
  'Suzuka Circuit': 'jp-1962',
  'Miami International Autodrome': 'us-2022',
  'Circuit Gilles Villeneuve': 'ca-1978',
  'Circuit de Monaco': 'mc-1929',
  'Circuit de Barcelona-Catalunya': 'es-1991',
  'Red Bull Ring': 'at-1969',
  'Silverstone Circuit': 'gb-1948',
  'Circuit de Spa-Francorchamps': 'be-1925',
  Hungaroring: 'hu-1986',
  'Circuit Park Zandvoort': 'nl-1948',
  'Autodromo Nazionale di Monza': 'it-1922',
  Madring: 'es-2026',
  'Baku City Circuit': 'az-2016',
  'Sepang International Circuit': 'my-1999',
  'Marina Bay Street Circuit': 'sg-2008',
  'Circuit of the Americas': 'us-2012',
  'Autódromo Hermanos Rodríguez': 'mx-1962',
  'Autódromo José Carlos Pace': 'br-1940',
  'Las Vegas Strip Street Circuit': 'us-2023',
  'Lusail International Circuit': 'qa-2004',
  'Yas Marina Circuit': 'ae-2009',
}

const SIZE = 100
const PAD = 4

async function load() {
  const path = process.argv[2]
  if (path) return JSON.parse(readFileSync(path, 'utf8'))
  const res = await fetch(SOURCE)
  if (!res.ok) throw new Error(`${SOURCE}: HTTP ${res.status}`)
  return res.json()
}

/** Equirectangular projection around the circuit's mean latitude, fitted to the box. */
function outline(coords) {
  const lat0 = (coords.reduce((a, [, lat]) => a + lat, 0) / coords.length) * (Math.PI / 180)
  const pts = coords.map(([lon, lat]) => [lon * Math.cos(lat0), -lat])
  const xs = pts.map((p) => p[0])
  const ys = pts.map((p) => p[1])
  const [minX, maxX, minY, maxY] = [Math.min(...xs), Math.max(...xs), Math.min(...ys), Math.max(...ys)]
  const scale = (SIZE - 2 * PAD) / Math.max(maxX - minX, maxY - minY)
  const w = (maxX - minX) * scale + 2 * PAD
  const h = (maxY - minY) * scale + 2 * PAD
  const xy = pts.map(([x, y]) => [((x - minX) * scale + PAD).toFixed(1), ((y - minY) * scale + PAD).toFixed(1)])
  const d = `M${xy.map(([x, y]) => `${x} ${y}`).join('L')}Z`
  return { d, width: Number(w.toFixed(1)), height: Number(h.toFixed(1)), start: xy[0].map(Number) }
}

const geo = await load()
const byId = new Map(geo.features.map((f) => [f.properties.id, f]))
const out = {}
for (const [name, id] of Object.entries(CIRCUITS)) {
  const feature = byId.get(id)
  if (!feature) throw new Error(`No circuit ${id} (${name}) in the dataset`)
  out[name] = { id, ...outline(feature.geometry.coordinates) }
}

writeFileSync(
  new URL('../src/data/tracks.ts', import.meta.url),
  `// Generated by scripts/build-tracks.mjs; do not edit by hand.
// Circuit outlines from bacinger/f1-circuits (MIT, (c) 2019-2025 Tomislav Bacinger),
// https://github.com/bacinger/f1-circuits. Keyed by the circuit name Jolpica uses.
export interface Track {
  id: string
  /** SVG path in a box of width by height (the longer side is ${SIZE}). */
  d: string
  width: number
  height: number
  /** The first point of the outline, near the start line. */
  start: [number, number]
}

export const TRACKS: Record<string, Track> = ${JSON.stringify(out, null, 2)}

export function trackFor(circuitName: string): Track | undefined {
  return TRACKS[circuitName]
}
`,
)
console.log(`Wrote ${Object.keys(out).length} tracks`)
